/* Generated By:JavaCC: Do not edit this line. SentenceParserTreeConstants.java Version 5.0 */
public interface SentenceParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSENTENCE = 1;
  public int JJTNP = 2;
  public int JJTCN = 3;
  public int JJTPP = 4;
  public int JJTVP = 5;


  public String[] jjtNodeName = {
    "Start",
    "Sentence",
    "NP",
    "CN",
    "PP",
    "VP",
  };
}
/* JavaCC - OriginalChecksum=187d658d414e027089a97ba36689d8ae (do not edit this line) */
