/* Generated By:JJTree&JavaCC: Do not edit this line. SentenceParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SentenceParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DETERMINER = 5;
  /** RegularExpression Id. */
  int NOUN = 6;
  /** RegularExpression Id. */
  int PRONOUN = 7;
  /** RegularExpression Id. */
  int VERB = 8;
  /** RegularExpression Id. */
  int ADJ = 9;
  /** RegularExpression Id. */
  int PREPOSITION = 10;
  /** RegularExpression Id. */
  int WORD = 11;
  /** RegularExpression Id. */
  int LETTER = 12;
  /** RegularExpression Id. */
  int PERIOD = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<DETERMINER>",
    "<NOUN>",
    "<PRONOUN>",
    "<VERB>",
    "<ADJ>",
    "<PREPOSITION>",
    "<WORD>",
    "<LETTER>",
    "\".\"",
  };

}
